import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { UserDataProvider } from "@/contexts/userDataContext";
import "./globals.css";
import Navigation from "@/components/organisms/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CamtLead",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${inter.className}  transition-colors duration-1000 bg-purple-550 dark:bg-purple-1000`}>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
